fix cicd

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -32,6 +32,13 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
+      - name: Check if tag already exists
+        run: |
+          if git rev-parse --verify --quiet "v${{ github.event.inputs.version }}"; then
+            echo "Version ${{ github.event.inputs.version }} already exists, aborting workflow."
+            exit 1
+          fi
+
       - name: Set the version
         run: |
           echo "GregTech Expert 2 ${{ env.FULL_VERSION }}" > ./overrides/resources/custommainmenu/version.txt
@@ -53,7 +60,7 @@ jobs:
       - name: Setup Python
         uses: actions/setup-python@v4
         with:
-          python-version: '3.10'
+          python-version: '3.11'
           cache: pip
 
       - name: Install dependencies
@@ -85,8 +92,9 @@ jobs:
 
       - name: Create GitHub Release
         uses: softprops/action-gh-release@v1
-        if: startsWith(github.ref, 'refs/tags/')
         with:
+          tag_name: "${{ env.FULL_VERSION }}"
+          draft: false
           prerelease: false
           generate_release_notes: true
           files: |
@@ -95,7 +103,7 @@ jobs:
             ./${{ env.NAME }}-${{ env.FULL_VERSION }}-server.zip
 
       - name: Upload Curseforge
-        uses: henkelmax/upload-curseforge-modpack-action@v2.0.0
+        uses: juraj-hrivnak/upload-curseforge-modpack-action@v2.0.0
         with: 
           api-token: ${{ secrets.CF_API_TOKEN }}
           project-id: '565238'
